name: Pamuk
description: The base plugin to run whiskers.
version: 1.0

authors: [Schaffer79, Admicos]
website: http://pamuk.whiskersofficial.org/

database: false
main: org.whiskersofficial.pamuk.PamukPlugin
